
name: Lint Code Base

on:
  push:
    branches-ignore: [ "note_branch" ]
    branches: [ "notes" ]
  pull_request:
    branches: [ "notes" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
       

      - name: Super-Linter
        uses: github/super-linter@v4.10.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
